.PHONY: start ios android web typecheck install

start:
	npx expo start

ios:
	npx expo start --ios

android:
	npx expo start --android

web:
	npx expo start --web

typecheck:
	npx tsc --noEmit

install:
	npm install
