package rules

// ASME20 is the authoritative list of 20 compliance rules derived from
// ASME A17.1 Safety Code for Elevators and Escalators.
//
// Each rule maps to exactly one telemetry metric stored in the TimescaleDB
// telemetry hypertable by the telemetry-ingestor service.
//
// Threshold semantics:
//   - Continuous metrics (current, temperature, time…): pass if value ≤ threshold
//   - Counters requiring service at N cycles: pass if value < threshold
//   - Boolean safety fields (stored as 1.0/0.0): pass if value == 1.0
var ASME20 = []Rule{
	// ── Motor subsystem ──────────────────────────────────────────────────────
	{
		ID:          "ASME-001",
		Description: "Motor Current Within Operational Range",
		ASMERef:     "ASME A17.1 §2.16 (Driving machines)",
		Metric:      "motor_current_a",
		Threshold:   20.0,
		Unit:        "A",
		PassMsg:     "Motor current within operational range",
		FailMsg:     "Motor current exceeds operational limit",
		evaluate:    func(v float64) bool { return v <= 20.0 },
	},
	{
		ID:          "ASME-002",
		Description: "Motor Temperature Below Maximum",
		ASMERef:     "ASME A17.1 §2.16.4 (Motor protection)",
		Metric:      "motor_temp_c",
		Threshold:   85.0,
		Unit:        "°C",
		PassMsg:     "Motor temperature within safe range",
		FailMsg:     "Motor temperature exceeds maximum",
		evaluate:    func(v float64) bool { return v <= 85.0 },
	},
	{
		ID:          "ASME-003",
		Description: "Motor Speed Within Rated Range",
		ASMERef:     "ASME A17.1 §2.16.1 (Driving machine speed)",
		Metric:      "motor_rpm",
		Threshold:   1800.0,
		Unit:        "RPM",
		PassMsg:     "Motor speed within rated range",
		FailMsg:     "Motor speed exceeds rated maximum",
		evaluate:    func(v float64) bool { return v <= 1800.0 },
	},
	{
		ID:          "ASME-004",
		Description: "Motor Hours Below Service Interval",
		ASMERef:     "ASME A17.1 §8.6.1 (Periodic maintenance tests)",
		Metric:      "motor_run_hours",
		Threshold:   20000.0,
		Unit:        "h",
		PassMsg:     "Motor hours within service interval",
		FailMsg:     "Motor hours exceed service interval — maintenance required",
		evaluate:    func(v float64) bool { return v < 20000.0 },
	},

	// ── Trip / usage ─────────────────────────────────────────────────────────
	{
		ID:          "ASME-005",
		Description: "Trip Count Below Major Inspection Threshold",
		ASMERef:     "ASME A17.1 §8.10 (Periodic inspections)",
		Metric:      "trip_count",
		Threshold:   500000.0,
		Unit:        "trips",
		PassMsg:     "Trip count within major inspection interval",
		FailMsg:     "Trip count has reached major inspection threshold",
		evaluate:    func(v float64) bool { return v < 500000.0 },
	},

	// ── Door subsystem ───────────────────────────────────────────────────────
	{
		ID:          "ASME-006",
		Description: "Door Close Force Within Safe Limit",
		ASMERef:     "ASME A17.1 §2.13.4 (Power closing of doors — closing force)",
		Metric:      "door_close_force_n",
		Threshold:   135.0,
		Unit:        "N",
		PassMsg:     "Door close force within safe limit",
		FailMsg:     "Door close force exceeds 135 N limit — auto-fail",
		evaluate:    func(v float64) bool { return v <= 135.0 },
	},
	{
		ID:          "ASME-007",
		Description: "Door Motor Current Within Spec",
		ASMERef:     "ASME A17.1 §2.13 (Power closing of doors)",
		Metric:      "door_motor_amps",
		Threshold:   5.0,
		Unit:        "A",
		PassMsg:     "Door motor current within spec",
		FailMsg:     "Door motor current exceeds specification",
		evaluate:    func(v float64) bool { return v <= 5.0 },
	},
	{
		ID:          "ASME-008",
		Description: "Door Close Time Within Limits",
		ASMERef:     "ASME A17.1 §2.13.6 (Door closing time)",
		Metric:      "door_close_time_ms",
		Threshold:   5000.0,
		Unit:        "ms",
		PassMsg:     "Door close time within limits",
		FailMsg:     "Door close time exceeds allowable limit",
		evaluate:    func(v float64) bool { return v <= 5000.0 },
	},
	{
		ID:          "ASME-009",
		Description: "Door Cycles Below Service Threshold",
		ASMERef:     "ASME A17.1 §8.6.3 (Door operator periodic tests)",
		Metric:      "door_cycle_count",
		Threshold:   2000000.0,
		Unit:        "cycles",
		PassMsg:     "Door cycle count within service threshold",
		FailMsg:     "Door cycle count has reached service threshold",
		evaluate:    func(v float64) bool { return v < 2000000.0 },
	},
	{
		ID:          "ASME-010",
		Description: "Door Obstruction Events Within Tolerance",
		ASMERef:     "ASME A17.1 §2.13.5 (Reopening device)",
		Metric:      "door_obstruction_events",
		Threshold:   10.0,
		Unit:        "events",
		PassMsg:     "Door obstruction events within tolerance",
		FailMsg:     "Excessive door obstruction events detected",
		evaluate:    func(v float64) bool { return v <= 10.0 },
	},

	// ── Brake subsystem ──────────────────────────────────────────────────────
	{
		ID:          "ASME-011",
		Description: "Brake Response Time Within Limit",
		ASMERef:     "ASME A17.1 §8.6.4.1 (Brake response test)",
		Metric:      "brake_response_ms",
		Threshold:   80.0,
		Unit:        "ms",
		PassMsg:     "Brake response time within limit",
		FailMsg:     "Brake response time exceeds 80 ms limit — auto-fail",
		evaluate:    func(v float64) bool { return v <= 80.0 },
	},
	{
		ID:          "ASME-012",
		Description: "Brake Holding Current Within Spec",
		ASMERef:     "ASME A17.1 §2.18 (Brakes)",
		Metric:      "brake_current_a",
		Threshold:   3.0,
		Unit:        "A",
		PassMsg:     "Brake holding current within spec",
		FailMsg:     "Brake holding current exceeds specification",
		evaluate:    func(v float64) bool { return v <= 3.0 },
	},
	{
		ID:          "ASME-013",
		Description: "Brake Engagements Below Service Threshold",
		ASMERef:     "ASME A17.1 §8.6.4 (Brake tests)",
		Metric:      "brake_engagement_count",
		Threshold:   500000.0,
		Unit:        "count",
		PassMsg:     "Brake engagement count within service threshold",
		FailMsg:     "Brake engagement count has reached service threshold",
		evaluate:    func(v float64) bool { return v < 500000.0 },
	},

	// ── Ride quality ─────────────────────────────────────────────────────────
	{
		ID:          "ASME-014",
		Description: "Leveling Accuracy Within ADA/ASME Limit",
		ASMERef:     "ASME A17.1 §2.29.2 / ADA §4.10.5 (Landing accuracy)",
		Metric:      "leveling_accuracy_mm",
		Threshold:   12.7,
		Unit:        "mm",
		PassMsg:     "Leveling accuracy within ½-inch ADA limit",
		FailMsg:     "Leveling accuracy exceeds 12.7 mm (½ inch) limit — auto-fail",
		evaluate:    func(v float64) bool { return v <= 12.7 },
	},
	{
		ID:          "ASME-015",
		Description: "Vibration Below Comfort and Safety Limit",
		ASMERef:     "ASME A17.1 §2.16.3 / ISO 18738-1 (Ride quality)",
		Metric:      "vibration_g",
		Threshold:   0.15,
		Unit:        "g",
		PassMsg:     "Vibration within comfort and safety limits",
		FailMsg:     "Vibration exceeds comfort and safety limit",
		evaluate:    func(v float64) bool { return v <= 0.15 },
	},

	// ── Safety circuits (boolean: 1.0 = ok, 0.0 = fault) ────────────────────
	{
		ID:          "ASME-016",
		Description: "Door Interlock Functional",
		ASMERef:     "ASME A17.1 §2.12.1 (Hoistway door interlock)",
		Metric:      "door_interlock_ok",
		Threshold:   1.0,
		Unit:        "bool",
		PassMsg:     "Door interlock is operational",
		FailMsg:     "Door interlock fault detected — immediate action required",
		evaluate:    func(v float64) bool { return v == 1.0 },
	},
	{
		ID:          "ASME-017",
		Description: "Overspeed Governor Functional",
		ASMERef:     "ASME A17.1 §2.17.3 (Overspeed governor)",
		Metric:      "governor_ok",
		Threshold:   1.0,
		Unit:        "bool",
		PassMsg:     "Overspeed governor is operational",
		FailMsg:     "Overspeed governor fault detected — immediate action required",
		evaluate:    func(v float64) bool { return v == 1.0 },
	},
	{
		ID:          "ASME-018",
		Description: "Buffers Functional",
		ASMERef:     "ASME A17.1 §2.22.1 (Buffers and bumpers)",
		Metric:      "buffer_ok",
		Threshold:   1.0,
		Unit:        "bool",
		PassMsg:     "Buffers are operational",
		FailMsg:     "Buffer fault detected — immediate action required",
		evaluate:    func(v float64) bool { return v == 1.0 },
	},
	{
		ID:          "ASME-019",
		Description: "Pit Stop Switch Functional",
		ASMERef:     "ASME A17.1 §2.26.9 (Hoistway pit)",
		Metric:      "pit_switch_ok",
		Threshold:   1.0,
		Unit:        "bool",
		PassMsg:     "Pit stop switch is operational",
		FailMsg:     "Pit stop switch fault detected — immediate action required",
		evaluate:    func(v float64) bool { return v == 1.0 },
	},
	{
		ID:          "ASME-020",
		Description: "Safety Circuit Continuous",
		ASMERef:     "ASME A17.1 §2.26.1 (Electrical protective devices)",
		Metric:      "safety_circuit_ok",
		Threshold:   1.0,
		Unit:        "bool",
		PassMsg:     "Safety circuit is continuous and operational",
		FailMsg:     "Safety circuit fault detected — auto-fail, immediate action required",
		evaluate:    func(v float64) bool { return v == 1.0 },
	},
}
